apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullName" . }}-secret-environment
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
type: Opaque
stringData:
  AMQP_URL: {{ .Values.amqp_url }}
  USER_KEY: {{ .Values.user_key }}
  AGENT_KEY: {{ .Values.agent_key }}
  DDS_API_URL: {{ .Values.dds_api_url }}
  TASK_QUEUE_NAME: {{ .Values.task_queue_name }}
