apiVersion: apps/v1
kind: Deployment
metadata:
  name: md5-reporter
  labels:
    version: {{VERSION}}
    git_commit: {{CI_COMMIT_SHA}}
    git_tag: {{CI_COMMIT_REF_SLUG}}
spec:
  template:
    spec:
      containers:
        - name: md5-reporter
          image: {{CI_IMAGE_NAME}}
