apiVersion: v1
kind: Secret
metadata:
  name: md5-reporter-secret-environment
stringData:
  AMQP_URL: {{AMQP_URL}}
  USER_KEY: {{USER_KEY}}
  AGENT_KEY: {{AGENT_KEY}}
  DDS_API_URL: {{DDS_API_URL}}
---
apiVersion: v1
kind: Secret
metadata:
  name: md5-reporter-pull
data:
  dockerconfigjson: {{DOCKER_CONFIG}}
